services:
  - type: web
    name: stelic-copilot
    runtime: python
    rootDir: copilot_web
    buildCommand: apt-get update -y && apt-get install -y default-jre-headless tesseract-ocr poppler-utils && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
